package com.mitendero.tribuo.mitendero.JPA;
// Generated Apr 14, 2017 8:01:04 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Compras generated by hbm2java
 */


public class Compras implements java.io.Serializable {

    private Integer idCompra;
    private Productos productos;
    private Sucursales sucursales;
    private int precioUnidad;
    private int cantidad;
    private Date fecha;

    public Compras() {
    }

    public Compras(Productos productos, Sucursales sucursales, int precioUnidad, int cantidad, Date fecha) {
        this.productos = productos;
        this.sucursales = sucursales;
        this.precioUnidad = precioUnidad;
        this.cantidad = cantidad;
        this.fecha = fecha;
    }


    public Integer getIdCompra() {
        return this.idCompra;
    }

    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }


    public Productos getProductos() {
        return this.productos;
    }

    public void setProductos(Productos productos) {
        this.productos = productos;
    }


    public Sucursales getSucursales() {
        return this.sucursales;
    }

    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }


    public int getPrecioUnidad() {
        return this.precioUnidad;
    }

    public void setPrecioUnidad(int precioUnidad) {
        this.precioUnidad = precioUnidad;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }


    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
