package com.mitendero.tribuo.mitendero.JPA;
// Generated Apr 14, 2017 8:01:04 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Marcas generated by hbm2java
 */

public class Marcas implements java.io.Serializable {

    private Integer idMarca;
    private Fabricantes fabricantes;
    private String nombreMarca;
    private Set<Productos> productoses = new HashSet<Productos>(0);

    public Marcas() {
    }

    public Marcas(Fabricantes fabricantes, String nombreMarca) {
        this.fabricantes = fabricantes;
        this.nombreMarca = nombreMarca;
    }

    public Marcas(Fabricantes fabricantes, String nombreMarca, Set<Productos> productoses) {
        this.fabricantes = fabricantes;
        this.nombreMarca = nombreMarca;
        this.productoses = productoses;
    }

    public Integer getIdMarca() {
        return this.idMarca;
    }

    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }

    public Fabricantes getFabricantes() {
        return this.fabricantes;
    }

    public void setFabricantes(Fabricantes fabricantes) {
        this.fabricantes = fabricantes;
    }

    public String getNombreMarca() {
        return this.nombreMarca;
    }

    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }

    public Set<Productos> getProductoses() {
        return this.productoses;
    }

    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }

}
