package com.mitendero.tribuo.mitendero.jpa;
// Generated Apr 14, 2017 8:01:04 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Presentaciones generated by hbm2java
 */

public class Presentaciones implements java.io.Serializable {

    private Integer idPresentacion;
    private int cantidad;
    private String unidadMedida;
    private Set<Productos> productoses = new HashSet<Productos>(0);

    public Presentaciones() {
    }

    public Presentaciones(int cantidad, String unidadMedida) {
        this.cantidad = cantidad;
        this.unidadMedida = unidadMedida;
    }

    public Presentaciones(int cantidad, String unidadMedida, Set<Productos> productoses) {
        this.cantidad = cantidad;
        this.unidadMedida = unidadMedida;
        this.productoses = productoses;
    }

    public Integer getIdPresentacion() {
        return this.idPresentacion;
    }

    public void setIdPresentacion(Integer idPresentacion) {
        this.idPresentacion = idPresentacion;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public String getUnidadMedida() {
        return this.unidadMedida;
    }

    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }

    public Set<Productos> getProductoses() {
        return this.productoses;
    }

    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }

}
