package com.mitendero.tribuo.mitendero.JPA;
// Generated Apr 14, 2017 8:01:04 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */

public class Productos implements java.io.Serializable {

    private Integer idProducto;
    private Marcas marcas;
    private Presentaciones presentaciones;
    private Subcategorias subcategorias;
    private String nombreProducto;
    private Integer precioSugerido;
    private String codigoBarras;
    private String descripcion;
    private String tipo;
    private Set<Ventas> ventases = new HashSet<Ventas>(0);
    private Set<Compras> comprases = new HashSet<Compras>(0);
    private Set<ProductosTiendas> productosTiendases = new HashSet<ProductosTiendas>(0);

    public Productos() {
    }

    public Productos(Marcas marcas, Presentaciones presentaciones, Subcategorias subcategorias, String nombreProducto, String codigoBarras, String tipo) {
        this.marcas = marcas;
        this.presentaciones = presentaciones;
        this.subcategorias = subcategorias;
        this.nombreProducto = nombreProducto;
        this.codigoBarras = codigoBarras;
        this.tipo = tipo;
    }

    public Productos(Marcas marcas, Presentaciones presentaciones, Subcategorias subcategorias, String nombreProducto, Integer precioSugerido, String codigoBarras, String descripcion, String tipo, Set<Ventas> ventases, Set<Compras> comprases, Set<ProductosTiendas> productosTiendases) {
        this.marcas = marcas;
        this.presentaciones = presentaciones;
        this.subcategorias = subcategorias;
        this.nombreProducto = nombreProducto;
        this.precioSugerido = precioSugerido;
        this.codigoBarras = codigoBarras;
        this.descripcion = descripcion;
        this.tipo = tipo;
        this.ventases = ventases;
        this.comprases = comprases;
        this.productosTiendases = productosTiendases;
    }


    public Integer getIdProducto() {
        return this.idProducto;
    }

    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }


    public Marcas getMarcas() {
        return this.marcas;
    }

    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }


    public Presentaciones getPresentaciones() {
        return this.presentaciones;
    }

    public void setPresentaciones(Presentaciones presentaciones) {
        this.presentaciones = presentaciones;
    }


    public Subcategorias getSubcategorias() {
        return this.subcategorias;
    }

    public void setSubcategorias(Subcategorias subcategorias) {
        this.subcategorias = subcategorias;
    }

    public String getNombreProducto() {
        return this.nombreProducto;
    }

    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    public Integer getPrecioSugerido() {
        return this.precioSugerido;
    }

    public void setPrecioSugerido(Integer precioSugerido) {
        this.precioSugerido = precioSugerido;
    }

    public String getCodigoBarras() {
        return this.codigoBarras;
    }

    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Set<Ventas> getVentases() {
        return this.ventases;
    }

    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }


    public Set<Compras> getComprases() {
        return this.comprases;
    }

    public void setComprases(Set<Compras> comprases) {
        this.comprases = comprases;
    }


    public Set<ProductosTiendas> getProductosTiendases() {
        return this.productosTiendases;
    }

    public void setProductosTiendases(Set<ProductosTiendas> productosTiendases) {
        this.productosTiendases = productosTiendases;
    }

}
