package com.mitendero.tribuo.mitendero.JPA;
// Generated Apr 14, 2017 8:01:04 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Subcategorias generated by hbm2java
 */

public class Subcategorias implements java.io.Serializable {

    private Integer idSubcategoria;
    private Categorias categorias;
    private String nombreSubcategoria;
    private Set<Productos> productoses = new HashSet<Productos>(0);

    public Subcategorias() {
    }

    public Subcategorias(Categorias categorias, String nombreSubcategoria) {
        this.categorias = categorias;
        this.nombreSubcategoria = nombreSubcategoria;
    }

    public Subcategorias(Categorias categorias, String nombreSubcategoria, Set<Productos> productoses) {
        this.categorias = categorias;
        this.nombreSubcategoria = nombreSubcategoria;
        this.productoses = productoses;
    }


    public Integer getIdSubcategoria() {
        return this.idSubcategoria;
    }

    public void setIdSubcategoria(Integer idSubcategoria) {
        this.idSubcategoria = idSubcategoria;
    }


    public Categorias getCategorias() {
        return this.categorias;
    }

    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }

    public String getNombreSubcategoria() {
        return this.nombreSubcategoria;
    }

    public void setNombreSubcategoria(String nombreSubcategoria) {
        this.nombreSubcategoria = nombreSubcategoria;
    }


    public Set<Productos> getProductoses() {
        return this.productoses;
    }

    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }

}
