package com.mitendero.tribuo.mitendero.JPA;
// Generated Apr 14, 2017 8:01:04 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Sucursales generated by hbm2java
 */

public class Sucursales implements java.io.Serializable {

    private int idSucursal;
    private Tiendas tiendas;
    private String direccion;
    private String ciudad;
    private Set<Ventas> ventases = new HashSet<Ventas>(0);
    private Set<ProductosTiendas> productosTiendases = new HashSet<ProductosTiendas>(0);
    private Set<Compras> comprases = new HashSet<Compras>(0);

    public Sucursales() {
    }

    public Sucursales(int idSucursal, Tiendas tiendas, String direccion, String ciudad) {
        this.idSucursal = idSucursal;
        this.tiendas = tiendas;
        this.direccion = direccion;
        this.ciudad = ciudad;
    }

    public Sucursales(int idSucursal, Tiendas tiendas, String direccion, String ciudad, Set<Ventas> ventases, Set<ProductosTiendas> productosTiendases, Set<Compras> comprases) {
        this.idSucursal = idSucursal;
        this.tiendas = tiendas;
        this.direccion = direccion;
        this.ciudad = ciudad;
        this.ventases = ventases;
        this.productosTiendases = productosTiendases;
        this.comprases = comprases;
    }


    public int getIdSucursal() {
        return this.idSucursal;
    }

    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }

    public Tiendas getTiendas() {
        return this.tiendas;
    }

    public void setTiendas(Tiendas tiendas) {
        this.tiendas = tiendas;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    public Set<Ventas> getVentases() {
        return this.ventases;
    }

    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }

    public Set<ProductosTiendas> getProductosTiendases() {
        return this.productosTiendases;
    }

    public void setProductosTiendases(Set<ProductosTiendas> productosTiendases) {
        this.productosTiendases = productosTiendases;
    }

    public Set<Compras> getComprases() {
        return this.comprases;
    }

    public void setComprases(Set<Compras> comprases) {
        this.comprases = comprases;
    }

}
