package com.mitendero.tribuo.mitendero.jpa;
// Generated Apr 14, 2017 8:01:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tiendas generated by hbm2java
 */

public class Tiendas implements java.io.Serializable {


    private Integer idTienda;
    private User user;
    private Integer nit;
    private int cedula;
    private String razonSocial;
    private Set<Sucursales> sucursaleses = new HashSet<Sucursales>(0);

    public Tiendas() {
    }

    public Tiendas(User user, int cedula, String razonSocial) {
        this.user = user;
        this.cedula = cedula;
        this.razonSocial = razonSocial;
    }

    public Tiendas(User user, Integer nit, int cedula, String razonSocial, Set<Sucursales> sucursaleses) {
        this.user = user;
        this.nit = nit;
        this.cedula = cedula;
        this.razonSocial = razonSocial;
        this.sucursaleses = sucursaleses;
    }

    public Integer getIdTienda() {
        return this.idTienda;
    }

    public void setIdTienda(Integer idTienda) {
        this.idTienda = idTienda;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Integer getNit() {
        return this.nit;
    }

    public void setNit(Integer nit) {
        this.nit = nit;
    }

    public int getCedula() {
        return this.cedula;
    }

    public void setCedula(int cedula) {
        this.cedula = cedula;
    }

    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    public Set<Sucursales> getSucursaleses() {
        return this.sucursaleses;
    }

    public void setSucursaleses(Set<Sucursales> sucursaleses) {
        this.sucursaleses = sucursaleses;
    }

}


