package com.mitendero.tribuo.mitendero.jpa;
// Generated Apr 14, 2017 8:01:04 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */

public class User implements java.io.Serializable {

    private Integer userId;
    private int active;
    private String email;
    private String lastName;
    private String name;
    private String password;
    private int contactNumber;
    private Set<Tiendas> tiendases = new HashSet<Tiendas>(0);
    private Set<Role> roles = new HashSet<Role>(0);

    public User() {
    }

    public User(int active, String email, String lastName, String name, String password, int contactNumber) {
        this.active = active;
        this.email = email;
        this.lastName = lastName;
        this.name = name;
        this.password = password;
        this.contactNumber = contactNumber;
    }

    public User(int active, String email, String lastName, String name, String password, int contactNumber, Set<Tiendas> tiendases, Set<Role> roles) {
        this.active = active;
        this.email = email;
        this.lastName = lastName;
        this.name = name;
        this.password = password;
        this.contactNumber = contactNumber;
        this.tiendases = tiendases;
        this.roles = roles;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public int getActive() {
        return this.active;
    }

    public void setActive(int active) {
        this.active = active;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getContactNumber() {
        return this.contactNumber;
    }

    public void setContactNumber(int contactNumber) {
        this.contactNumber = contactNumber;
    }

    public Set<Tiendas> getTiendases() {
        return this.tiendases;
    }

    public void setTiendases(Set<Tiendas> tiendases) {
        this.tiendases = tiendases;
    }

    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

}
